### ISSUE TITLE
ADDED FEATURES for FINAL MOCK DEFENSE!

### ISSUE THREAD

**Issue by shayiii0714** [lunestelle/PHP_Sakaycle#45]
## 🛠️TO IMPLEMENT and UPDATE 😴🥱😕

- [x] Implement the `3 notices` for `Expired Franchises` and `Change of Motorcycle` and addtional for `dropped notice` (Every 15days)
  - Also, place the fixed penalty fees on SMS and Email notifications (note: sa katu ning January 21 na reminder na nag expired na apila nalang pd sa notices)
  - Also, for ` expired  == franchises` the `fee` wil be placed at the top of the Appoinment Information  together with the `penalty fee` 
- [x] Place a Fees for every transaction
  - Freezone/Zone 1 
  - Zone 2 -4
  - Place the fee at the top of the Appointment Information
- [x] Update the Tricycles Page that it will be filtered by `STATUSES`
- [x] Change the all the Logo's in emails and the words `SAKAYCLE` to `OTOFA`
   
![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/79b4af0a-2aeb-467b-bc05-72e98982f9bc)
   - 
![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/e087f905-1ef7-4637-86a1-531004c1a0c5)

## 🔁ALIAS NAME:
`Sakaycle` sub-domain name change to `OTOFA` ---> `ORMOC TRICYCLE ONLINE FRANCHISE APPOINTMENT`

**Comment by lunestelle** [comment]
### **IMPLEMENTED & UPDATED FEATURES**

- Change this from` License Validity` to `License Expiry Date` on the driver feature. `Also added validation on this that the expiry date should be in the future and not the current date or the past`.
- The Driver Feature addition of new drivers has been updated that will only appear if there are CIN numbers that still lack a driver, ensuring that each tricycle CIN is assigned only one driver.

![image](https://github.com/lunestelle/PHP_Sakaycle/assets/119985247/3ae09c6c-0ac1-4789-ada5-e65c2d6d2dad)

- Implemented `Driver Statuses for Driver Feature` which will have statuses `"Active, Driver's License Expired, and Inactive"`
    - Created a new automation to `retrieve active drivers whose license expiry date is either today or a past date`. It checks if the driver already has the `"Driver License Expired"` status. **If not, it sends SMS & Email notifications, inserts the status, and updates the last_notification_date field on the driver table on the database. If the `"Driver License Expired"` status still exists, it checks the last notification date and sends notifications again if it's been more than 15 days.**
    - The  `"Driver License Expired"` status will be removed only once the operator edits the driver details and updates its `license_expiry_date`
       - **Check the zip file for the Notification Images:** [Driver License Expiration Notifs Images.zip](https://github.com/lunestelle/PHP_Sakaycle/files/14073765/Driver.License.Expiration.Notifs.Images.zip)



❗ **P.S: Could you please update all features that utilize badges (which are mainly used in the statuses column on the pages)? One of Maam Apple's comments suggests that they might tempt users to click on them since they resemble buttons.**

**Comment by shayiii0714** [comment]
## 👍 NO ISSUE: 😃

💹 Added the Maintenance Tracker feature to the operator
💹 Added the Taripa feature to the operator where they can view and print taripa of their chosen year. This feature will show even though the user still doesn't have a CIN.
💹 Change this from `License Validity` to `License Expiry Date` on the driver feature. `Also added validation on this that the expiry date should be in the future and not the current date or the past.`

## COMMENT:

> Can't  `EXPORT CSV FILE` button since it is one button rendered for operator and admin
> Can't check the `expired licensed` status of the `drivers` on my local.

## TO FIX/UPATE:

- [ ] Send all the automation emails and sms notifications for documenation.
- [ ]  Change the all the Logo's in emails and the words `SAKAYCLE` to `OTOFA`
- [ ] Edit button should not visible when the appointment `status` == `approved`
![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/104abb8c-2878-40e8-8074-bb5b2414c046)

**Comment by lunestelle** [comment]
### **WIP** 😃 

-  Implement the 3 notices for Expired Franchises and Change of Motorcycle and additional for dropped notices (Every 15days)

**1st Notice**
![image](https://github.com/lunestelle/PHP_Sakaycle/assets/119985247/f006e6a5-cd94-4cb1-b039-88b7160dd6c1)

**2nd Notice**
![image](https://github.com/lunestelle/PHP_Sakaycle/assets/119985247/0c533aee-8d6b-488d-bf33-573a082e0e0d)

**3rd Notice**
![image](https://github.com/lunestelle/PHP_Sakaycle/assets/119985247/e02fdebb-7941-4a7a-a9ec-e095b41d54a0)

**Comment by shayiii0714** [comment]
## NO ISSUE:
- On `tricycles` page the `operator` and `admin` can filter the data using the `STATUS`
- Creating a new  and editing an `appointment` the corresponding fees will be displayed.

## UPDATE:
- Update the UI on assessment fees
- Update the style on `Tricycle Reports`

## COMMENT:
> Can't check the automations and other related on that like:
  - The expired status (renewal / change motor)
  - Notices and force drop due to unable to renew.
## TO UPDATE:

- [ ] On emails change the `sakaycle@gmail.com` to `otofa@gmail.com`
![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/fe61eb54-5ab4-4f7c-a6b2-4f4ad3f198ed)
- [ ] Don't forget to change the `Website Title`, `Web-icon`, and the `Homepage Logo`
![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/5a9da62a-0198-4d3b-9018-a29791681fad)

**Comment by lunestelle** [comment]
### 📝 TO DO LIST:

- [ ] **Implement Print Feature for Tricycle CIN:**
  - Implement the print feature for Tricycle CIN on both the operator and admin sides.

- [ ] **Update Automation Notifications:**
  - Update the automation notifications for expired renewal and expired motor to include the number of notices sent and mention that only up to 3 notices will be sent.

- [ ] **Update Appointment Processes Notifications:**
  - Update the appointment processes notifications.

- [ ] **Hide `div` Based on Route Selection:**
  - Please hide this `div`, it should only show if a `route` is selected.
  - ![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/f658c834-e28c-41a1-95da-ac6cae3f7303)

- [ ] **Change Website Title, Web-icon, and Homepage Logo:**
  - Don't forget to change the `Website Title`, `Web-icon`, and the `Homepage Logo`.
  - ![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/5a9da62a-0198-4d3b-9018-a29791681fad)

- [ ] **Fix Active Links for `ADD NEW DRIVER` and `EDIT DRIVER`:**
  - Please fix the active link for `ADD NEW DRIVER` and `EDIT DRIVER`.
  - ![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/79779a5d-d5d8-49da-b027-b9a9cba3a695)
  - ![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/081106b9-f69d-418e-9d68-38860ad7ce5f)

- [ ] **Show `NEW` Button After Adding a New Driver:**
  - The `NEW` button for adding a new driver is not showing after adding a driver.
  - ![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/cdd820f4-c2a3-4133-9147-69d395ac1d3c)
  - ![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/f9898ba5-a1c5-469a-ade3-0d40ece9dcd6)

- [ ] **Fix Tricycle CIN Selection Issue:**
  - Also, when adding a new driver, there are 2 active tricycles, but only 1 CIN showed on the selection.
  - ![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/602f38db-bec3-4163-bda5-34751c93f6e1)

- [ ] **Reveal `NEW` Button After Editing Driver Status:**
  - After editing the status of the driver, the `NEW` button will appear again.
  - ![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/3003a081-f68f-4cdc-8cd7-fd04f8ea682b)

- [ ] **Verify Phone Number Update in Manage Account:**
  - Update the manage account so that when the phone number is changed or updated by the user, it should set the phone number to be verified again.

**Comment by lunestelle** [comment]
![freezone](https://github.com/lunestelle/PHP_Sakaycle/assets/119985247/3ef1bfdf-004d-4169-a449-a5ecbdec0bba)

**Comment by shayiii0714** [comment]
## 👍  NO ISSUE: 😄 

💹 Hide div Based on Route Selection:
  - Please hide this div, it should only show if a route is selected.

💹  Fix Tricycle CIN Selection Issue:
  - Also, when adding a new driver, there are 2 active tricycles, but only 1 CIN showed on the selection.
  
💹  Fix Active Links for ADD NEW DRIVER and EDIT DRIVER:
  - Please fix the active link for ADD NEW DRIVER and EDIT DRIVER.

💹 Fix Maintenance Log
  - Fix Maintenance Log where it shows a driver name even though the user didn't have a driver for that CIN

💹 Verify Phone Number Update in Manage Account:
  - Update the managed account so that when the phone number is changed or updated by the user, it should set the phone number to be verified again.

💹  Update Operators Feature (Admin Side):
  - Implement that it will display all operators who possess either "Active" or "Dropped" tricycles. This ensures that  operators without their own CIN numbers are still visible.

💹   Update the Operators count on the Dashboard Feature (Admin Side):
  - Implement that the feature will counts operators correctly if they have tricycles marked as "Active" and "Dropped." It also makes sure to include operators who used to have CIN numbers in the total count.

💹  Update the Appointment Reports Feature (Admin Side):
  - Integrate new columns and create a hyperlink directing users to specific statuses.

💹 Update the Appointments (Operator) / Appointment Approval (Admin) Feature:
  - Implement a filter status

💹  Update the Inquiries Feature:
  - Implement a message and response status filter

💹  Update the Maintenance Log Feature:
  - Implement a Driver Name filter

## ⭐ 🌟 ⭐

**Comment by lunestelle** [comment]
### 📝 TO DO LIST:

- [ ] **Implement Print Feature for Tricycle CIN:**  **(THIS IS ALREADY WORK IN PROGRESS)**
  - Implement the print feature for Tricycle CIN on both the operator and admin sides.

- [ ] I suggest putting a `DOWNLOAD PDF` for the `Tricycle Taripa` on the `OPERATOR` side. If ever, they don't have their printer to print it immediately.

 - [x] **Update Dashboard Feature and its related pages (zone pages):**
  - Update the content or data used for showing the chart.
  - Update the Zone Pages where it should contain the barangays from the `Taripa Table` in the database instead of the hardcoded data.
  
![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/0b0056e7-c224-46ea-b33c-4d5e9a9f3948)

![image](https://github.com/lunestelle/PHP_Sakaycle/assets/119985247/a93c1c6a-4281-4d74-9b36-fbb7b1ed14dc)

- [ ] **Update Automation Notifications:**
  - Update the automation notifications for expired renewal and expired motor to include the number of notices sent and mention that only up to 3 notices will be sent.

- [ ] **Update Appointment Processes Notifications:**
  - Update the appointment process notifications.

- [ ] **Change Website Title, Web-icon, and Homepage Logo:**
  - Don't forget to change the `Website Title`, `Web-icon`, and the `Homepage Logo` on live hosting.
  
![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/5a9da62a-0198-4d3b-9018-a29791681fad)
