### ISSUE TITLE
UPDATED FEATURES FOR FINAL MOCK DEFENSE! (PART 2)

### ISSUE THREAD

**Issue by lunestelle** [lunestelle/PHP_Sakaycle#47]
## ✅ Implemented! 😊

- [x] **Update Taripa Feature:**
  - Users (Admin or Operator) should be able to print and download the Taripa. The displayed data should correspond to the selected year in the filter.
  - Fix related issues on the dashboard and the view tricycle page.
  - **Taripa Page** | [Taripa](https://github.com/lunestelle/PHP_Sakaycle/assets/119985247/2dfb0cb8-f4bf-40b5-bb8f-952516ced63c)
  - **View Tricycle Page** | [View Tricycle Page](https://github.com/lunestelle/PHP_Sakaycle/assets/119985247/33df4e85-aafe-496c-804b-58ff9c7016c5)

- [x] **Add DOWNLOAD PDF Option for Tricycle Taripa on OPERATOR Side:**
  - Add a `DOWNLOAD PDF` option for the `Tricycle Taripa` on the `OPERATOR` side to provide an alternative for users without immediate access to a printer. [Download PDF](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/0b0056e7-c224-46ea-b33c-4d5e9a9f3948)

- [x] **Update Dashboard Feature and its Related Pages (Zone Pages):**
  - Updated chart content.
  - Updated Zone Pages to include barangays from the `Taripa Table` in the database instead of hardcoded data.
  - [Dashboard Update](https://github.com/lunestelle/PHP_Sakaycle/assets/119985247/a93c1c6a-4281-4d74-9b36-fbb7b1ed14dc)

- [x] **Fix Total Appointments Display Issue in Appointment Reports:**
  - Resolved the issue where no data was displayed in the table when clicking the hyperlinked number in `TOTAL APPOINTMENTS` on `APPOINTMENT REPORTS`.

- [x] **Add Operator Name Filter in Maintenance Tracker on Admin Side:**
  - Implemented the Operator's Name filter in the `MAINTENANCE TRACKER` on the `ADMIN SIDE`.

## ℹ️ Database Update Notice:

I've made significant updates to the database, including the addition of new tables and columns. Please ensure these changes are reflected in the documents.

#### Tables Updated:

- **Drivers Table:**
  - Changed: `license_validity` ➡️ `license_expiry_date`   
  - Added: `last_notification_date` 

- **Driver Statuses Table (New)**

- **Tricycles Table:**
  - Added: `expired_notification_sent_at` 
  - Added: `expired_change_motor_notification_sent_at` 

- **Taripa Table:**
  - Changed: `effective_year` ➡️ `effective_date`
  - Changed: `regular_rate` ➡️ `regular_fare`
  - Changed: `student_rate` ➡️ `discounted_fare`
  - Removed: `senior_and_pwd_rate`

- **Rate Adjustments Table:**
  - Changed: `effective_year` ➡️ `effective_date`

📂 **Updated SQL File**: [sakaycle (02-01-24).zip](https://github.com/lunestelle/PHP_Sakaycle/files/14115228/sakaycle.02-01-24.zip)

**Related Issue:** [Link to Issue](https://github.com/lunestelle/PHP_Sakaycle/issues/45#issue-2095852011)

**Comment by shayiii0714** [comment]
## NO ISSUE: 😄 ⭐ 

💹 Update Dashboard Feature and its Related Pages (Zone Pages):
  - Updated chart content.
  - Updated Zone Pages to include barangays from the Taripa Table in the database instead of hardcoded data.
  
  ⏫ I want to check the part when generaing a new taripa is the latest taripa will reflect on `Taripa Page` and `Dashboard Page`.

💹 Fix Total Appointments Display Issue in Appointment Reports:
  - Resolved the issue where no data was displayed in the table when clicking the hyperlinked number in TOTAL APPOINTMENTS on APPOINTMENT REPORTS.

## ❗ FOUND ISSUE: ❗ 

> Add DOWNLOAD PDF Option for Tricycle Taripa on OPERATOR Side:
>   - Add a DOWNLOAD PDF option for the Tricycle Taripa on the OPERATOR side to provide an alternative for users without immediate access to a printer.

- [ ] When clicking the `DONWLOAD PDF` the UI will be different as if there's an issue but you can see it was loading until the downloaded pdf will save. Then, will turn back to its original UI.

 - ![image](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/ab6b926a-da9e-4735-9c00-0491fb97b45c)

- [ ] **DOWLOADED PDF FILE** --- the content did not fit on one long bondpaper. The UI is different from `PRINT` file

  - [DOWNLOADED FILE](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/cc5a6be3-052a-463b-9e61-f3c6f39d71d0)
  

> Update Taripa Feature:
>   - Users (Admin or Operator) should be able to print and download the Taripa. The displayed data should correspond to the selected year in the filter.
>   - Fix related issues on the dashboard and the view tricycle page.

- [ ] Cannot generate a new `TARIPA` | [See Photo](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/7f49e872-f97c-4698-a990-3cccba335bb1)
   - But if you back the page it, the generated  taripa will show. I think the error shows only upon clicking the `calculate` for generating a new taripa | [See Photo](https://github.com/lunestelle/PHP_Sakaycle/assets/102460202/e8047593-4b66-43b7-ac69-ec12d76cc4a3)
 

- [ ] I think the validation on generating a new taripa is up to 2-3 years like it is not limited to the current year. For example, the LGU once to create an advance taripa, so before the 2025 end they will create a new taripa pero the effective date is on January 21,2025. What do you think? @lunestelle

**Comment by lunestelle** [comment]
## 📝 TO DO LIST:

- [ ] **Update Automation Notifications:**
  - Update automation notifications for expired renewal and expired motor, mentioning the number of notices sent and that only up to 3 notices will be sent.

- [ ] **Update Appointment Processes Notifications:**
  - Update appointment process notifications.

- [ ] **Change Website Title, Web-icon, and Homepage Logo:**
  - Update the `Website Title`, `Web-icon`, and the `Homepage Logo` on live hosting.

- [ ] **Issue with Generating New TARIPA:**
  - The problem arises when attempting to generate a new TARIPA that already exists. To address this, I've enhanced the validation process. Now, users cannot create a new TARIPA if it already exists, ensuring TARIPAs are unique.

![image](https://github.com/lunestelle/PHP_Sakaycle/assets/119985247/61032d0c-d6c1-4b56-b818-de6d90ef76c6)

**Comment by lunestelle** [comment]
🛠️ TO IMPLEMENT and UPDATE 😴🥱😕

- [ ] **Taripa Generation Validation:**
  - The current system appears to limit taripa generation to the current year. However, considering scenarios where LGUs may need to create advance taripas before the current year ends, adjustments may be necessary. For instance, creating a new taripa effective from January 21, 2025, before the year ends.
  - Unfortunately, I'm currently encountering unexpected issues in implementing the taripa generation validation, causing delays. Consequently, I'm unable to implement the feature allowing taripa generation beyond the current year at this moment. Your patience and understanding are appreciated as I work to resolve these issues. 🤣 😆

- [ ] **Update the Appointment Process:**
  - Enhance the appointment process to restrict users from setting appointments for renewal and change motor only when their tricycle has the status `Renewal Required` or `Expired Renewal` or `Change Motor Required` or `Expired Motor`.

- [ ] **Tricycle Appointment Frequency Limitation:**
  - Ensure that a tricycle can only set an appointment once per year, preventing multiple appointments for the same tricycle within the same year.

- [ ] **Implement Calendar Feature:**
  - Explore the feasibility of implementing a calendar feature to facilitate scheduling and organization within the system.
